name: Actions@bot

on:
  push:
    branches:
      - master
    paths:
      - "bot/**"

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Move files to root
        run: cp -r bot/. . && rm -r bot site
